[project]
name = "mypythoneditor"
include = ["**/*"]

[phases.setup]
commands = []

[phases.install]
commands = [
  "python3 -m pip install --upgrade pip",
  "pip3 install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
commands = [
  "python3 app.py"
]
