[project]
name = "mypythoneditor"
include = ["**/*"]

[phases.setup]
commands = []

[phases.install]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
commands = []

[phases.start]
commands = [
  "python app.py"
]
